Repository HKN-UCSD/hkn-server, pull requests merged in 2020-07, with the labels that each got.

#21 Added base AuthMiddleware and OfficerAuth and MemberAuth.
  package-lock.json
  package.json
  src/constants/authErrorMessages.ts
  src/constants/userRoles.ts
  src/index.ts
  src/middlewares/authentication/authFunctions/index.ts
  src/middlewares/authentication/base/authentication.middleware.ts
  src/services/auth.service.ts
Labels: dev experience, enhancement

#11 Added signup endpoint to server.
  README.md
  package-lock.json
  package.json
  src/config.ts
  src/constants/ErrResponses.ts
  src/controllers/auth.controller.ts
  src/index.ts
  src/routers/auth.router.ts
Labels: feature

#23 Circleci project setup for hkn-server
  .circleci/config.yml
  src/index.ts
Labels: dev experience

#25 Added run_build and run_linter_prettier jobs for CircleCI.
  .circleci/config.yml
  src/config.ts
  src/constants/ErrResponses.ts
  src/controllers/auth.controller.ts
  src/routers/auth.router.ts
Labels: dev experience

#29 Added joi middleware to provide a good way of validating req.body.
  package-lock.json
  package.json
  src/constants/ErrResponses.ts
  src/constants/authErrorMessages.ts
  src/middlewares/authentication/base/authentication.middleware.ts
  src/middlewares/validation/base/validation.middleware.ts
  src/services/auth.service.ts
  src/services/validate.service.ts
Labels: dev experience, enhancement

#30 Email integration using SendGrid
  .gitignore
  package-lock.json
  package.json
  src/services/email/email.definition.ts
  src/services/email/email.service.ts
Labels: dev experience, feature

#33 Added rate limiting to all endpoints so we don't get DDOS-ed.
  package-lock.json
  package.json
  src/index.ts
Labels: low priority
