Repository HKN-UCSD/hkn-server, pull requests merged in 2020-09, with the labels that each got.

#87 Seed to local postgres running in Docker.
  .circleci/config.yml
  ormconfig.js
  package.json
  src/entities/AppUser.ts
  src/entities/Attendance.ts
  src/entities/Event.ts
  src/entities/RSVP.ts
  src/migrations/1598829375940-TypeORMMetadata.ts
  src/migrations/1598831126707-InitialSchema.ts
  src/seeds/0-InitialSeed.ts
  src/tests/EventController.test.ts
  tsconfig.json
Labels: dependencies

#90 Added minor changes to the codebase.
  package-lock.json
  package.json
  src/controllers/UserController.ts
  src/services/AuthenticationService.ts
Labels: bug, dev experience

#95 Added signup endpoint for AppUsers with non-guest role to signup.
  src/controllers/AuthController.ts
  src/controllers/OldAuthController.ts
  src/controllers/UserController.ts
  src/controllers/index.ts
  src/payloads/AppUser.ts
  src/payloads/index.ts
  src/routers/AuthRouter.ts
  src/services/AccountService.ts
  src/services/AppUserService.ts
  src/services/index.ts
Labels: feature

#106 Made create user request payload's major and graduation year optional.
  src/controllers/UserController.ts
  src/payloads/AppUser.ts
Labels: enhancement

#107 Drop inheritance for Event payloads.
  src/payloads/Event.ts
Labels: enhancement

#112 Add and update more docs
  README.md
  guides/add/add_new_mapper.md
  guides/add/add_new_payload.md
  guides/caution.md
  guides/naming/mapper.md
  guides/naming/payload.md
Labels: documentation
